package view;

import controller.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Cesar A. Villamizar C.
 */
public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                if (Kairos.showConfirmDialog()) {
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        buttonsPane = new javax.swing.JPanel();
        datePane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabsPane = new javax.swing.JTabbedPane();
        file = new javax.swing.JPanel();
        openSesButton = new javax.swing.JButton();
        saveSesButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        newSesButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        cleanButton = new javax.swing.JButton();
        randomChoiseButton = new javax.swing.JButton();
        view = new javax.swing.JPanel();
        deactivateButton = new javax.swing.JToggleButton();
        coloByPlacesButton = new javax.swing.JToggleButton();
        progressBarButton = new javax.swing.JToggleButton();
        colorSchedButton = new javax.swing.JToggleButton();
        help = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Kairos "+controller.Kairos.VERSION);
        setMinimumSize(new java.awt.Dimension(640, 580));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"6:00-7:00", null, null, null, null, null, null, null},
                {"7:00-8:00", null, null, null, null, null, null, null},
                {"8:00-9:00", null, null, null, null, null, null, null},
                {"9:00-10:00", null, null, null, null, null, null, null},
                {"10:00-11:00", null, null, null, null, null, null, null},
                {"11:00-12:00", null, null, null, null, null, null, null},
                {"12:00-13:00", null, null, null, null, null, null, null},
                {"13:00-14:00", null, null, null, null, null, null, null},
                {"14:00-15:00", null, null, null, null, null, null, null},
                {"15:00-16:00", null, null, null, null, null, null, null},
                {"16:00-17:00", null, null, null, null, null, null, null},
                {"17:00-18:00", null, null, null, null, null, null, null},
                {"18:00-19:00", null, null, null, null, null, null, null},
                {"19:00-20:00", null, null, null, null, null, null, null},
                {"20:00-21:00", null, null, null, null, null, null, null},
                {"21:00-22:00", null, null, null, null, null, null, null}
            },
            new String [] {
                "Hora", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buttonsPane.setLayout(new javax.swing.BoxLayout(buttonsPane, javax.swing.BoxLayout.X_AXIS));
        jScrollPane2.setViewportView(buttonsPane);

        jLabel1.setText("Grupos actualizados el dia --/--/--  --:--");

        javax.swing.GroupLayout datePaneLayout = new javax.swing.GroupLayout(datePane);
        datePane.setLayout(datePaneLayout);
        datePaneLayout.setHorizontalGroup(
            datePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        datePaneLayout.setVerticalGroup(
            datePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        openSesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/open alt.png"))); // NOI18N
        openSesButton.setText("Abrir");
        openSesButton.setToolTipText("");
        openSesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openSesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openSesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSesButtonActionPerformed(evt);
            }
        });

        saveSesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/Save.png"))); // NOI18N
        saveSesButton.setText("Guardar");
        saveSesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveSesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveSesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSesButtonActionPerformed(evt);
            }
        });

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/quit.png"))); // NOI18N
        exitButton.setText("Salir");
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        newSesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/new doc.png"))); // NOI18N
        newSesButton.setText("Nuevo");
        newSesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newSesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newSesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSesButtonActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        javax.swing.GroupLayout fileLayout = new javax.swing.GroupLayout(file);
        file.setLayout(fileLayout);
        fileLayout.setHorizontalGroup(
            fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newSesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openSesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveSesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fileLayout.setVerticalGroup(
            fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLayout.createSequentialGroup()
                .addGroup(fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(saveSesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(openSesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newSesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabsPane.addTab("Archivo", file);

        cleanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/gnome_edit_clear.png"))); // NOI18N
        cleanButton.setText("Limpiar");
        cleanButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cleanButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });

        randomChoiseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/knob_shuffle_on.png"))); // NOI18N
        randomChoiseButton.setText("Aleatorio");
        randomChoiseButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        randomChoiseButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        randomChoiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomChoiseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editLayout = new javax.swing.GroupLayout(edit);
        edit.setLayout(editLayout);
        editLayout.setHorizontalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(randomChoiseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cleanButton)
                .addContainerGap(734, Short.MAX_VALUE))
        );
        editLayout.setVerticalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editLayout.createSequentialGroup()
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cleanButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(randomChoiseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabsPane.addTab("Edición", edit);

        deactivateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/sad.png"))); // NOI18N
        deactivateButton.setText("Filtrar por cupos");
        deactivateButton.setToolTipText("Desactiva los grupos sin cupos disponibles");
        deactivateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deactivateButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deactivateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateButtonActionPerformed(evt);
            }
        });

        coloByPlacesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/colorFont.png"))); // NOI18N
        coloByPlacesButton.setText("Color por cupos");
        coloByPlacesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        coloByPlacesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        coloByPlacesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coloByPlacesButtonActionPerformed(evt);
            }
        });

        progressBarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/progress.png"))); // NOI18N
        progressBarButton.setText("Barra de cupos");
        progressBarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        progressBarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        progressBarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressBarButtonActionPerformed(evt);
            }
        });

        colorSchedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/color.png"))); // NOI18N
        colorSchedButton.setText("Horario a color");
        colorSchedButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        colorSchedButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        colorSchedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorSchedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deactivateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coloByPlacesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorSchedButton)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progressBarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coloByPlacesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deactivateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorSchedButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        tabsPane.addTab("Vista", view);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/info.png"))); // NOI18N
        jButton5.setText("Acerca de");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout helpLayout = new javax.swing.GroupLayout(help);
        help.setLayout(helpLayout);
        helpLayout.setHorizontalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addContainerGap(799, Short.MAX_VALUE))
        );
        helpLayout.setVerticalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpLayout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        tabsPane.addTab("Ayuda", help);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(datePane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabsPane)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        clearSelection();
    }//GEN-LAST:event_cleanButtonActionPerformed

    private void randomChoiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomChoiseButtonActionPerformed
        randomChoise();
    }//GEN-LAST:event_randomChoiseButtonActionPerformed

    private void newSesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSesButtonActionPerformed
        if (Kairos.showConfirmDialog()) {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new NewSesion().setVisible(true);
                }
            });
        }
    }//GEN-LAST:event_newSesButtonActionPerformed

    private void openSesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSesButtonActionPerformed
        if (Kairos.showConfirmDialog() && Kairos.cargarSesion()) {
            clearTable();
            init();
        }
    }//GEN-LAST:event_openSesButtonActionPerformed

    private void saveSesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSesButtonActionPerformed
        Kairos.guardarSesion();
    }//GEN-LAST:event_saveSesButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        if (Kairos.showConfirmDialog()) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void deactivateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateButtonActionPerformed
        filterByPlaces = !filterByPlaces;
        actualizarBotones();
    }//GEN-LAST:event_deactivateButtonActionPerformed

    private void coloByPlacesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coloByPlacesButtonActionPerformed
        colorByPlaces = !colorByPlaces;
        for (Asignatura mat : Kairos.getSubjects()) {
            for (Button boton : mat.getButtons()) {
                boton.colorButton(colorByPlaces);
            }
        }
    }//GEN-LAST:event_coloByPlacesButtonActionPerformed

    private void progressBarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressBarButtonActionPerformed
        progressBar = !progressBar;
        for (Asignatura mat : Kairos.getSubjects()) {
            for (Button boton : mat.getButtons()) {
                boton.enableProgressBar(progressBar);
            }
        }
    }//GEN-LAST:event_progressBarButtonActionPerformed

    private void colorSchedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorSchedButtonActionPerformed
        colorSched = !colorSched;
        if (colorSched) {
            jTable1.setDefaultRenderer(Object.class, new CustomCellRenderer());
        } else {
            jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer());
        }
        jTable1.repaint();
    }//GEN-LAST:event_colorSchedButtonActionPerformed

    public void init() {
        if (Kairos.getSesionDate() != null) {
            this.jLabel1.setText("Grupos actualizados el dia " + sdf.format(Kairos.getSesionDate()));
        } else {
            this.jLabel1.setText("Grupos actualizados el dia --/--/--  --:--");
        }
        this.buttonsPane.removeAll();
        this.buttonsPane.add(Box.createRigidArea(new Dimension(15, 0)));

        for (Asignatura mat : Kairos.getSubjects()) {

            JPanel panel = new JPanel();
            panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
            panel.add(mat.getLabel());

            for (Group grup : mat.getGrupos()) {
                Button boton = new Button(grup, mat);
                panel.add(boton);
                panel.add(boton.getProgressBar());

                boton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        Button bot = (Button) ae.getSource();
                        if (bot.isSelected()) {
                            if (bot.getMateria().isSelected()) {
                                bot.setSelected(false);
                                for (Button boton : bot.getMateria().getButtons()) {
                                    if (boton.isSelected()) {
                                        boton.doClick();
                                        break;
                                    }
                                }
                                bot.setSelected(true);
                            }
                            bot.getMateria().setSelected(true);
                        } else {
                            bot.getMateria().setSelected(false);
                        }
                        selectButton(bot);
                        addBloq(bot);
                    }
                });
            }
            panel.add(Box.createVerticalGlue());
            this.buttonsPane.add(panel);
            this.buttonsPane.add(Box.createHorizontalGlue());
            this.buttonsPane.add(Box.createRigidArea(new Dimension(15, 0)));
            this.buttonsPane.validate();
        }
    }

    private void addBloq(Button boton) {
        Group grupo = boton.getGrupo();
        for (Block bloque : grupo.getHorario()) {
            String value = null;
            if (boton.isSelected()) {
                value = bloque.getSalon() + ": " + boton.getMateria().getNombre();
            }
            for (int j = bloque.getHora(); j < bloque.getHoraFin(); j++) {
                jTable1.setValueAt(value, j - 6, bloque.getDia());
            }
        }
    }

    private void clearSelection() {
        for (Asignatura mat : Kairos.getSubjects()) {
            if (mat.isSelected()) {
                for (Button bot : mat.getButtons()) {
                    if (bot.isSelected()) {
                        bot.doClick();
                        break;
                    }
                }
            }
        }
    }

    private void clearTable() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
            {"6:00-7:00", null, null, null, null, null, null, null},
            {"7:00-8:00", null, null, null, null, null, null, null},
            {"8:00-9:00", null, null, null, null, null, null, null},
            {"9:00-10:00", null, null, null, null, null, null, null},
            {"10:00-11:00", null, null, null, null, null, null, null},
            {"11:00-12:00", null, null, null, null, null, null, null},
            {"12:00-13:00", null, null, null, null, null, null, null},
            {"13:00-14:00", null, null, null, null, null, null, null},
            {"14:00-15:00", null, null, null, null, null, null, null},
            {"15:00-16:00", null, null, null, null, null, null, null},
            {"16:00-17:00", null, null, null, null, null, null, null},
            {"17:00-18:00", null, null, null, null, null, null, null},
            {"18:00-19:00", null, null, null, null, null, null, null},
            {"19:00-20:00", null, null, null, null, null, null, null},
            {"20:00-21:00", null, null, null, null, null, null, null},
            {"21:00-22:00", null, null, null, null, null, null, null}
        },
                new String[]{
            "Hora", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"
        }));
    }

    private void randomChoise() {
        for (Asignatura materia : Kairos.getSubjects()) {
            if (!materia.isSelected()) {
                ArrayList<Button> botones = new ArrayList<>();
                for (Button bot : materia.getButtons()) {
                    if (bot.isEnabled()) {
                        botones.add(bot);
                    }
                }
                if (!botones.isEmpty()) {
                    Random rand = new Random();
                    Button bot = botones.get(rand.nextInt(botones.size()));
                    bot.doClick();
                }
            }
        }
    }

    private void actualizarBotones() {
        for (Asignatura mat : Kairos.getSubjects()) {
            for (Button boton : mat.getButtons()) {
                onOffButton(boton);
            }
        }
    }

    private void onOffButton(Button boton) {
        boolean p = boton.getConflictiveAmount() == 0; // V= no tiene conflictos
        boolean r = boton.isSelected(); // V= boton actual esta activo
        boolean s = boton.getGrupo().getCupos() > 0;// V= el grupo tiene cupos disponibles
        if (r || (p && (!filterByPlaces || s))) {
            boton.setEnabled(true);
        } else {
            boton.setEnabled(false);
        }
    }

    private void selectButton(Button bot) {
        for (Asignatura mat : Kairos.getSubjects()) {
            if (!mat.equals(bot.getMateria())) {
                for (Button boton : mat.getButtons()) {
                    if (bot.getGrupo().isOverlappedWith(boton.getGrupo())) {
                        if (bot.isSelected()) {
                            boton.addConflictive();
                        } else {
                            boton.removeConflictive();
                        }
                    }
                    onOffButton(boton);
                }
            }
        }
    }
    private boolean colorSched = false;
    private boolean colorByPlaces = false;
    private boolean progressBar = false;
    private boolean filterByPlaces = false;
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy  HH:mm");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPane;
    private javax.swing.JButton cleanButton;
    private javax.swing.JToggleButton coloByPlacesButton;
    private javax.swing.JToggleButton colorSchedButton;
    private javax.swing.JPanel datePane;
    private javax.swing.JToggleButton deactivateButton;
    private javax.swing.JPanel edit;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel file;
    private javax.swing.JPanel help;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton newSesButton;
    private javax.swing.JButton openSesButton;
    private javax.swing.JToggleButton progressBarButton;
    private javax.swing.JButton randomChoiseButton;
    private javax.swing.JButton saveSesButton;
    private javax.swing.JTabbedPane tabsPane;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}

class CustomCellRenderer extends DefaultTableCellRenderer {

    private final Color alt2 = new Color(242, 242, 242);
    private final Color alt1 = Color.WHITE;

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component cr = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        if (column > 0) {
            if (value != null) {
                String name = (String) value;
                Color color = new Color(name.split(":")[1].hashCode());
                setBackground(color);
                setForeground(new Color(255 - color.getRed(), 255 - color.getGreen(), 255 - color.getBlue()));
            } else {
                setBackground(colorAlternator(row));
                setForeground(Color.BLACK);
            }
        } else {
            setBackground(colorAlternator(row));
            setForeground(Color.BLACK);
        }
        return cr;
    }

    private Color colorAlternator(int row) {
        if ((row % 2) == 0) {
            return alt1;
        } else {
            return alt2;
        }
    }
}