package view;

import controller.*;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.io.IOException;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Cesar A. Villamizar C.
 */
public class NewSesion extends javax.swing.JFrame {

    /**
     * Creates new form NewSesion
     */
    public NewSesion() {
        try {
            buscador = new SIAConnection();            
        } catch (Exception ex) {
            showConnectionProblemDialog(new javax.swing.JFrame());
        }
        
        asignaturas = new ArrayList<>();
        asignaturasToAdd = new ArrayList<>();

        initComponents();
        if (Kairos.getSubjects() != null && !Kairos.getSubjects().isEmpty());
        {
            for (Asignatura asig : Kairos.getSubjects()) {
                Asignatura a = new Asignatura(asig.getNombre(), asig.getCodigo());
                a.setCreditos(asig.getCreditos());
                asignaturasToAdd.add(a);
            }
            refreshToAddList();
        }

        jProgressBar1.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionButtonPane = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        searchPane = new javax.swing.JPanel();
        planPane = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        posButton = new javax.swing.JRadioButton();
        preButton = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        planComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        subjectPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        titlePane = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        searchAddPane = new javax.swing.JPanel();
        addRemovePane = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        removeAllButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        creditsLabel1 = new javax.swing.JLabel();
        creditsLabel = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        toAddPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        toAddScrollPane = new javax.swing.JScrollPane();
        toAddList = new javax.swing.JList();
        resultsPane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        resultsScrollPane = new javax.swing.JScrollPane();
        resultsList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kairos "+Kairos.VERSION);
        setMinimumSize(new java.awt.Dimension(800, 550));

        okButton.setText("INICIAR");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Cargar archivo de sesión");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        jProgressBar1.setIndeterminate(true);

        javax.swing.GroupLayout optionButtonPaneLayout = new javax.swing.GroupLayout(optionButtonPane);
        optionButtonPane.setLayout(optionButtonPaneLayout);
        optionButtonPaneLayout.setHorizontalGroup(
            optionButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionButtonPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton)
                .addContainerGap())
        );
        optionButtonPaneLayout.setVerticalGroup(
            optionButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionButtonPaneLayout.createSequentialGroup()
                .addGroup(optionButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionButtonPaneLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(optionButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(okButton)
                            .addComponent(loadButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionButtonPaneLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        posButton.setText("Pos-grado");
        posButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posButtonActionPerformed(evt);
            }
        });

        preButton.setText("Pre-grado");
        preButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Nivel académico:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(preButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(posButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(preButton)
                .addComponent(posButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel9))
        );

        planComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccione un nivel académico--" }));
        planComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planComboBoxActionPerformed(evt);
            }
        });

        jLabel10.setText("Plan de estudios:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(planComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel10))
        );

        javax.swing.GroupLayout planPaneLayout = new javax.swing.GroupLayout(planPane);
        planPane.setLayout(planPaneLayout);
        planPaneLayout.setHorizontalGroup(
            planPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        planPaneLayout.setVerticalGroup(
            planPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planPaneLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Ingrese el nombre o código de la asignatura que desea buscar:");

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(searchTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout subjectPaneLayout = new javax.swing.GroupLayout(subjectPane);
        subjectPane.setLayout(subjectPaneLayout);
        subjectPaneLayout.setHorizontalGroup(
            subjectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(subjectPaneLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        subjectPaneLayout.setVerticalGroup(
            subjectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectPaneLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout searchPaneLayout = new javax.swing.GroupLayout(searchPane);
        searchPane.setLayout(searchPaneLayout);
        searchPaneLayout.setHorizontalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPaneLayout.createSequentialGroup()
                .addComponent(planPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80)
                .addComponent(subjectPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchPaneLayout.setVerticalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(planPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(subjectPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        titlePane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cesar A. Villamizar C.", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo.png"))); // NOI18N

        javax.swing.GroupLayout titlePaneLayout = new javax.swing.GroupLayout(titlePane);
        titlePane.setLayout(titlePaneLayout);
        titlePaneLayout.setHorizontalGroup(
            titlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePaneLayout.setVerticalGroup(
            titlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8)
        );

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/plus.png"))); // NOI18N
        addButton.setText("Agregar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/minus white.png"))); // NOI18N
        removeButton.setText(" Eliminar");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        removeAllButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/edit_clear.png"))); // NOI18N
        removeAllButton.setText("Limpiar");
        removeAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Créditos totales:");

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));
        jPanel4.add(filler1);

        creditsLabel1.setFont(new java.awt.Font("Serif", 0, 24));
        creditsLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/numbers/0.png"))); // NOI18N
        jPanel4.add(creditsLabel1);

        creditsLabel.setFont(new java.awt.Font("Serif", 0, 24));
        creditsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/numbers/0.png"))); // NOI18N
        jPanel4.add(creditsLabel);
        jPanel4.add(filler2);

        javax.swing.GroupLayout addRemovePaneLayout = new javax.swing.GroupLayout(addRemovePane);
        addRemovePane.setLayout(addRemovePaneLayout);
        addRemovePaneLayout.setHorizontalGroup(
            addRemovePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(removeAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addRemovePaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addRemovePaneLayout.setVerticalGroup(
            addRemovePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRemovePaneLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(addButton)
                .addGap(2, 2, 2)
                .addComponent(removeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeAllButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setText("(Créditos:Nombre de la Asignatura)");

        jLabel2.setText("Asignaturas a agregar:");

        toAddList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toAddListMouseClicked(evt);
            }
        });
        toAddScrollPane.setViewportView(toAddList);

        javax.swing.GroupLayout toAddPaneLayout = new javax.swing.GroupLayout(toAddPane);
        toAddPane.setLayout(toAddPaneLayout);
        toAddPaneLayout.setHorizontalGroup(
            toAddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toAddPaneLayout.createSequentialGroup()
                .addGroup(toAddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(toAddScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );
        toAddPaneLayout.setVerticalGroup(
            toAddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toAddPaneLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toAddScrollPane))
        );

        jLabel4.setText("Resultados de la búsqueda:");

        jLabel5.setText("(Créditos:Nombre de la Asignatura)");

        resultsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultsListMouseClicked(evt);
            }
        });
        resultsScrollPane.setViewportView(resultsList);

        javax.swing.GroupLayout resultsPaneLayout = new javax.swing.GroupLayout(resultsPane);
        resultsPane.setLayout(resultsPaneLayout);
        resultsPaneLayout.setHorizontalGroup(
            resultsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsPaneLayout.createSequentialGroup()
                .addGroup(resultsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(resultsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );
        resultsPaneLayout.setVerticalGroup(
            resultsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsPaneLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultsScrollPane))
        );

        javax.swing.GroupLayout searchAddPaneLayout = new javax.swing.GroupLayout(searchAddPane);
        searchAddPane.setLayout(searchAddPaneLayout);
        searchAddPaneLayout.setHorizontalGroup(
            searchAddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchAddPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addRemovePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toAddPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchAddPaneLayout.setVerticalGroup(
            searchAddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toAddPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addRemovePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(resultsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionButtonPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchAddPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchAddPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionButtonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        final String searchParameter = searchTextField.getText().replaceAll("-", "").replaceAll("%", "");             
        if (searchParameter.length() >= 3) {
            class MyWorker extends SwingWorker {

                @Override
                protected String doInBackground() {
                    jProgressBar1.setVisible(true);
                    jLabel6.setText("Buscando...");
                    allButtonsSetEnable(false);
                    try {
                        Plan plan= Plan.NULL_PLAN;
                        if(planComboBox.getSelectedIndex()!=0){
                            plan= (Plan)planComboBox.getSelectedItem();
                        }                        
                        asignaturas = buscador.buscarAsignaturas(searchParameter,plan);
                    } catch (IOException ex) {
                        showConnectionProblemDialog(new javax.swing.JFrame());
                    } finally {
                        return "Done.";
                    }
                }

                @Override
                protected void done() {
                    allButtonsSetEnable(true);
                    jProgressBar1.setVisible(false);
                    jLabel6.setText("");
                    refreshResultsList();
                }
            }
            new MyWorker().execute();
        } else {
            JOptionPane.showMessageDialog(this, "Digite mínimo 3 caracteres.", "Búsqueda inválida", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        if (Kairos.cargarSesion()) {
            invokeMainFrame();
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        searchButtonActionPerformed(evt);
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (!asignaturasToAdd.isEmpty()) {
            Kairos.getSubjects().clear();
            showFunnyMessage();
            class MyWorker extends SwingWorker {

                @Override
                protected String doInBackground() {
                    jProgressBar1.setVisible(true);
                    allButtonsSetEnable(false);
                    try {
                        for (Asignatura asig : asignaturasToAdd) {
                            jLabel6.setText("Cargando \"" + asig.getNombre() + "\"...");
                            //buscador.setPlanFilter(asig.getPlan());
                            Kairos.getSubjects().add(buscador.asignaturaCompleta(asig));
                        }
                        Kairos.setSesionDate(new GregorianCalendar().getTime());
                        Kairos.setSavedSesion(false);
                        invokeMainFrame();
                    } catch (IOException ex) {
                        showConnectionProblemDialog(new javax.swing.JFrame());
                        allButtonsSetEnable(true);
                        jProgressBar1.setVisible(false);
                        jLabel6.setText("");
                        Kairos.getSubjects().clear();
                    } finally {
                        return "Done.";
                    }
                }

                @Override
                protected void done() {
                }
            }
            new MyWorker().execute();
        } else {
            JOptionPane.showMessageDialog(this, "Agregue una o más asignaturas o cargue una sesión anterior para continuar.", "No hay asignaturas seleccionadas", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void resultsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultsListMouseClicked
        javax.swing.JList list = (javax.swing.JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            addSubjectToSelection((Asignatura) list.getSelectedValue());
            refreshToAddList();
        }
    }//GEN-LAST:event_resultsListMouseClicked

    private void toAddListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toAddListMouseClicked
        javax.swing.JList list = (javax.swing.JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            asignaturasToAdd.remove((Asignatura) list.getSelectedValue());
            refreshToAddList();
        }
    }//GEN-LAST:event_toAddListMouseClicked

    private void removeAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllButtonActionPerformed
        asignaturasToAdd.clear();
        refreshToAddList();
    }//GEN-LAST:event_removeAllButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        for (Object selected : toAddList.getSelectedValuesList()) {
            asignaturasToAdd.remove((Asignatura) selected);
        }
        refreshToAddList();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        for (Object selected : resultsList.getSelectedValuesList()) {
            addSubjectToSelection((Asignatura) selected);
        }
        refreshToAddList();
    }//GEN-LAST:event_addButtonActionPerformed

    private void preButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preButtonActionPerformed
        if (posButton.isSelected()) {
            posButton.setSelected(false);
        }
        refreshPlansList();

    }//GEN-LAST:event_preButtonActionPerformed

    private void planComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planComboBoxActionPerformed
        
    }//GEN-LAST:event_planComboBoxActionPerformed

    private void posButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posButtonActionPerformed
        if (preButton.isSelected()) {
            preButton.setSelected(false);
        }
        refreshPlansList();

    }//GEN-LAST:event_posButtonActionPerformed

    private void refreshPlansList() {
        try {
            if (preButton.isSelected()) {
                planComboBox.setModel(new javax.swing.DefaultComboBoxModel(buscador.getPlansPreg().toArray()));
            } else if (posButton.isSelected()) {
                planComboBox.setModel(new javax.swing.DefaultComboBoxModel(buscador.getPlansPos().toArray()));
            } else {
                String[] s = {"--Seleccione un nivel académico--"};
                planComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(s));                
            }
        } catch (Exception ex) {
            showConnectionProblemDialog(this);
            if(preButton.isSelected())preButton.setSelected(false);
            if(posButton.isSelected())posButton.setSelected(false);
        }
    }

    private void addSubjectToSelection(Asignatura toAdd) {
        int credits = toAdd.getCreditos();
        for (Asignatura a : asignaturasToAdd) {
            credits += a.getCreditos();
            if (a.equals(toAdd)) {
                return;
            }
            if (credits > Kairos.MAX_CREDITS) {
                JOptionPane.showMessageDialog(this, "Máximo de " + Kairos.MAX_CREDITS + " créditos alcanzados", "Creditos máximos", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        if (preButton.isSelected() || posButton.isSelected()) {
            toAdd.setPlan((Plan) planComboBox.getSelectedItem());
        }else{
            toAdd.setPlan(Plan.NULL_PLAN);
        }
        asignaturasToAdd.add(toAdd);
    }

    private void showFunnyMessage() {
        int cred = 0;
        if (!asignaturasToAdd.isEmpty()) {
            for (Asignatura a : asignaturasToAdd) {
                cred += a.getCreditos();
            }
        }
        String m = Kairos.returnFunnyMSG(cred);
        if (m != null) {
            JOptionPane.showMessageDialog(this, m, "Atención", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void allButtonsSetEnable(boolean b) {
        okButton.setEnabled(b);
        addButton.setEnabled(b);
        removeButton.setEnabled(b);
        removeAllButton.setEnabled(b);
        searchButton.setEnabled(b);
        loadButton.setEnabled(b);        
    }

    private void showCredits() {
        int creditos = 0;
        if (!asignaturasToAdd.isEmpty()) {
            for (Asignatura a : asignaturasToAdd) {
                creditos += a.getCreditos();
            }
        }
        int creditsDec = creditos / 10;
        creditos = creditos % 10;
        creditsLabel.setIcon(getNumberIcon(creditos));
        creditsLabel1.setIcon(getNumberIcon(creditsDec));
    }

    private void invokeMainFrame() {        
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MainFrame fr = new MainFrame();
                fr.setExtendedState(MAXIMIZED_BOTH);
                fr.setVisible(true);
                fr.init();
            }
        });
    }

    private void refreshToAddList() {
        javax.swing.DefaultListModel listModel = new javax.swing.DefaultListModel();
        for (Asignatura a : asignaturasToAdd) {
            listModel.addElement(a);
        }
        toAddList.setModel(listModel);
        showCredits();
        jLabel2.setText("Asignaturas a agregar: " + asignaturasToAdd.size());
    }

    private void refreshResultsList() {
        javax.swing.DefaultListModel listModel = new javax.swing.DefaultListModel();
        resultsList.setModel(listModel);
        for (Asignatura asig : asignaturas) {
            listModel.addElement(asig);
        }
        jLabel4.setText("Resultados de la búsqueda: " + asignaturas.size());
    }

    private javax.swing.ImageIcon getNumberIcon(int i) {
        javax.swing.ImageIcon icn = new javax.swing.ImageIcon(getClass().getResource("/view/icon/numbers/0.png"));
        if (i > 0 && i < 10) {
            icn = new javax.swing.ImageIcon(getClass().getResource("/view/icon/numbers/" + i + ".png"));
        }
        return icn;
    }
    
    public static void showConnectionProblemDialog(javax.swing.JFrame frame){
        JOptionPane.showMessageDialog(frame, "No se ha podido establecer conexión con el servidor.\nCargue una sesión manualmente o vuelva a intentarlo más tarde.", "Error de conexión", JOptionPane.WARNING_MESSAGE);
    }
    
    private SIAConnection buscador;
    private ArrayList<Asignatura> asignaturas;
    private ArrayList<Asignatura> asignaturasToAdd;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addRemovePane;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JLabel creditsLabel1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel optionButtonPane;
    private javax.swing.JComboBox planComboBox;
    private javax.swing.JPanel planPane;
    private javax.swing.JRadioButton posButton;
    private javax.swing.JRadioButton preButton;
    private javax.swing.JButton removeAllButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JList resultsList;
    private javax.swing.JPanel resultsPane;
    private javax.swing.JScrollPane resultsScrollPane;
    private javax.swing.JPanel searchAddPane;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPane;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JPanel subjectPane;
    private javax.swing.JPanel titlePane;
    private javax.swing.JList toAddList;
    private javax.swing.JPanel toAddPane;
    private javax.swing.JScrollPane toAddScrollPane;
    // End of variables declaration//GEN-END:variables
}
